import database.create_balance_sheets_table
import database.create_income_statements_table
import database.create_ticker_info_table

database.create_balance_sheets_table.run()
database.create_income_statements_table.run()
database.create_ticker_info_table.run()
