import database.create_balance_sheet_table
import database.create_income_statement_table
import database.create_ticker_info_table

database.create_balance_sheet_table.run()
database.create_income_statement_table.run()
database.create_ticker_info_table.run()
