[project]
name = "alexandria"
version = "0.1.0"
description = "Stock and cryptocurrency analysis tool."
readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
    "fastapi[standard]>=0.115.7",
    "yfinance>=0.2.51",
]
